export const resources = {
  'pt-BR': {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Carregando', retry: 'Tentar novamente', cancel: 'Cancelar', save: 'Salvar alterações', create: 'Criar', delete: 'Excluir', remove: 'Remover', search: 'Buscar', actions: 'Ações', status: 'Status', pending: 'Pendente', pending_approval: 'Aguardando aprovação', active: 'Ativo', invited: 'Convidado', suspended: 'Suspenso', removed: 'Removido', archived: 'Arquivado', openMenu: 'Abrir menu', expandSidebar: 'Expandir sidebar', collapseSidebar: 'Recolher sidebar', close: 'Fechar', previous: 'Anterior', next: 'Próxima', page: 'Página {{current}} de {{total}}', noResults: 'Nenhum resultado', edit: 'Editar', unknown: 'Não informado', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Escuro', system: 'Sistema', signOut: 'Sair', account: 'Conta', menu: 'Menu', email: 'E-mail', password: 'Senha', name: 'Nome', tenant: 'Organização', workspace: 'Workspace', members: 'pessoas', projects: 'projetos', updatedAt: 'Atualizado em', createdAt: 'Criado em', permissions: 'Permissões', accessDenied: 'Acesso negado', backHome: 'Voltar à visão geral', notFound: 'Página não encontrada', notFoundDescription: 'O endereço pode ter mudado ou não existe.', errorTitle: 'Não foi possível carregar', errorDescription: 'Confira sua conexão e tente novamente.'
      },
      auth: {
        title: 'Bem-vindo de volta', subtitle: 'Administre organizações, projetos e permissões com segurança.', brandKicker: 'Personas criadas com contexto', brandStatement: 'Crie personas consistentes para responder pesquisas com mais clareza.', emailPlaceholder: 'voce@empresa.com', passwordPlaceholder: 'Sua senha', showPassword: 'Mostrar senha', hidePassword: 'Ocultar senha', rememberMe: 'Lembrar-me neste dispositivo', submit: 'Entrar', submitting: 'Entrando…', invalidCredentials: 'E-mail ou senha incorretos.', pendingApproval: 'Seu cadastro ainda aguarda aprovação de um administrador.', inactiveAccount: 'Sua conta está inativa. Fale com um administrador.', genericError: 'Não foi possível entrar agora. Tente novamente.', secureSession: 'Sua sessão é protegida por cookie seguro. A senha nunca fica salva neste dispositivo.', expired: 'Sua sessão expirou. Entre novamente.'
      },
      authCarousel: { label: 'Recursos da PersonaIA', controls: 'Controles do carrossel', pause: 'Pausar apresentação', play: 'Continuar apresentação', goToSlide: 'Ver slide {{number}}: {{title}}', researchTitle: 'Entenda o que as pessoas realmente dizem', researchDescription: 'Organize respostas e transforme sinais dispersos em contexto útil para sua pesquisa.', personasTitle: 'Crie personas consistentes em minutos', personasDescription: 'Modele perfis genéricos com motivações, comportamentos e linguagem alinhados ao seu objetivo.', decisionsTitle: 'Leve insights claros para cada decisão', decisionsDescription: 'Compare perspectivas, refine hipóteses e mantenha projetos e equipes no mesmo contexto.', simulationTitle: 'Antecipe respostas antes de ir a campo', simulationDescription: 'Simule como diferentes perfis podem responder ao questionário e refine hipóteses com mais confiança.', governanceTitle: 'Mantenha cada projeto no contexto certo', governanceDescription: 'Organize personas, equipes e permissões por organização sem misturar dados ou responsabilidades.' },
      registration: { eyebrow: 'Novo acesso', title: 'Seja bem-vindo', subtitle: 'Informe o código da sua organização. O acesso será liberado após a aprovação de um administrador.', namePlaceholder: 'Seu nome completo', emailPlaceholder: 'voce@empresa.com', tenantPlaceholder: 'empresa-exemplo', tenantCode: 'Código da organização', tenantHint: 'Peça este código ao administrador da sua organização.', confirmPassword: 'Confirmar senha', confirmPasswordPlaceholder: 'Repita sua senha', passwordMismatch: 'As senhas não coincidem.', submit: 'Solicitar cadastro', submitting: 'Enviando…', requestSent: 'Solicitação de cadastro enviada.', successTitle: 'Cadastro aguardando aprovação', successDescription: 'Recebemos seus dados. Você poderá entrar assim que um administrador aprovar e ativar sua conta.', backToLogin: 'Voltar ao login', alreadyHaveAccount: 'Já tem uma conta?', noAccount: 'Ainda não tem acesso?', createAccount: 'Criar conta', invalidTenant: 'O código da organização é inválido ou está inativo.' },
      validation: { required: 'Campo obrigatório.', email: 'Informe um e-mail válido.', passwordLength: 'Use pelo menos 8 caracteres.' },
      forms: {
        error: 'Não foi possível concluir. Revise os dados e tente novamente.', created: 'Cadastro concluído com sucesso.', moved: 'Usuário movido para o novo projeto.', tenantName: 'Nome da organização', slug: 'Identificador', segment: 'Segmento', initialAdmin: 'Administrador inicial', passwordHint: 'Use 12 ou mais caracteres, com maiúscula, minúscula, número e símbolo.', description: 'Descrição', projects: 'Projetos iniciais', projectsHint: 'Opcional. Você poderá alterar os projetos depois.', initialPermission: 'Permissão inicial', selectTenant: 'Selecione uma organização', selectWorkspace: 'Selecione um workspace', selectProject: 'Selecione um projeto', fromProject: 'Projeto de origem', toProject: 'Projeto de destino', moveUser: 'Mover entre projetos', createTenantTitle: 'Nova organização e administrador', createTenantDescription: 'A organização será criada isoladamente com seu primeiro administrador e um workspace padrão.', createWorkspaceTitle: 'Novo workspace', createWorkspaceDescription: 'Organize projetos e acessos em um espaço exclusivo desta organização.', createAdminTitle: 'Novo administrador', createAdminDescription: 'O administrador terá acesso somente à organização selecionada.', createProjectTitle: 'Novo projeto', createProjectDescription: 'O projeto ficará permanentemente vinculado ao workspace selecionado.', createUserTitle: 'Novo usuário', createUserDescription: 'Cadastre a pessoa e, se quiser, atribua projetos e um preset de permissão.', moveUserTitle: 'Mover {{name}}', moveUserDescription: 'O acesso será removido do projeto de origem e criado no destino.', validation: { name: 'Use pelo menos 2 caracteres.', slug: 'Use apenas letras minúsculas, números e hífens.', password: 'A senha não atende aos requisitos de segurança.', tenant: 'Selecione uma organização.', workspace: 'Selecione um workspace.', user: 'Informe a identidade do usuário.', differentProject: 'Escolha um projeto diferente do projeto de origem.' }
      },
      notifications: { title: 'Notificações', titleWithUnread: 'Notificações, {{count}} não lidas', empty: 'Tudo em dia', emptyDescription: 'Novas atividades importantes aparecerão aqui.', markAllRead: 'Marcar todas como lidas', loading: 'Carregando notificações', loadError: 'Não foi possível carregar as notificações.', updateError: 'Não foi possível atualizar a notificação.', unread: 'Não lida', resolved: 'Solicitação resolvida', accessRequestedTitle: 'Novo pedido de acesso', accessRequestedDescription: '{{userName}} ({{userEmail}}) solicitou acesso a {{tenantName}}.', newActivity: 'Nova atividade', newActivityDescription: 'Há uma nova atualização para revisar.' },
      nav: { platform: 'Plataforma', organization: 'Organização', overview: 'Visão geral', accessControl: 'Controle de acessos', tenants: 'Organizações', admins: 'Administradores', workspaces: 'Workspaces', projects: 'Projetos', users: 'Usuários', permissions: 'Permissões', personas: 'Personas', questionnaires: 'Questionários' },
      context: { scope: 'Contexto de trabalho', client: 'Organização', workspace: 'Workspace', selectClient: 'Selecione uma organização', selectClientDescription: 'Escolha a organização para visualizar seus dados isolados.', selectWorkspace: 'Selecione um workspace', selectWorkspaceDescription: 'Escolha o workspace para configurar acessos e permissões.', allWorkspaces: 'Todos os workspaces' },
      accessControl: { title: 'Controle de acessos', superDescription: 'Aprove cadastros por organização e administre identidades globais em áreas separadas.', clientDescription: 'Aprove e gerencie usuários comuns da sua própria organização.', viewLabel: 'Tipo de controle de acesso', clientAccess: 'Acesso da organização', platformIdentities: 'Identidades da plataforma', platformEmptyDescription: 'As identidades globais cadastradas aparecerão aqui.', membershipCount: '{{count}} vínculos com organizações', globalRole: 'Papel global', standardIdentity: 'Identidade padrão', defaultClient: 'Organização padrão', editPlatformTitle: 'Acesso global de {{name}}', editPlatformDescription: 'Esta área altera somente o papel e o estado global da identidade.', search: 'Buscar por nome ou e-mail', filterLabel: 'Filtrar usuários por status', filters: { ALL: 'Todos', PENDING: 'Pendentes', ACTIVE: 'Ativos', SUSPENDED: 'Inativos', ARCHIVED: 'Reprovados' }, empty: 'Nenhum usuário neste filtro', emptyDescription: 'Novas solicitações de cadastro e contas gerenciáveis aparecerão aqui.', role: 'Perfil de acesso na organização', platform: 'Plataforma', you: '(você)', approve: 'Aprovar', reject: 'Reprovar', activate: 'Ativar', deactivate: 'Inativar', editAccess: 'Alterar acesso', editTitle: 'Acesso de {{name}}', editDescription: 'Esta alteração vale somente para a organização selecionada.', approved: 'Cadastro aprovado e acesso liberado.', rejected: 'Cadastro reprovado.', updated: 'Acesso atualizado.', securityWarning: 'Papéis e estados são aplicados somente nesta organização. Outros vínculos da identidade permanecem preservados.', platformSecurityWarning: 'Alterações globais encerram as sessões abertas. Vínculos por organização permanecem separados e devem ser administrados na área de acesso da organização.' },
      dashboard: {
        title: 'Visão geral',
        superDescription: 'Acompanhe os indicadores globais, a criação de projetos e personas e as solicitações de acesso da plataforma.',
        clientDescription: 'Acompanhe os indicadores, projetos, personas e acessos da sua organização.',
        userDescription: 'Veja os projetos aos quais seu acesso foi liberado.',
        periodFilter: 'Período dos dados',
        ranges: { '7d': '7 dias', '30d': '30 dias', '12m': '12 meses', '5y': '5 anos' },
        keyIndicators: 'Indicadores principais',
        projectsCreated: 'Projetos criados',
        personasCreated: 'Personas criadas',
        activeUsers: 'Usuários ativos',
        pendingAccessRequests: 'Pedidos aguardando aprovação',
        createdInPeriod: 'Total no período selecionado: {{period}}.',
        activeUsersDescription: 'Contas com acesso ativo neste momento.',
        pendingAccessRequestsDescription: 'Solicitações que ainda precisam da decisão de um administrador.',
        accessibleProjects: 'Projetos com acesso',
        accessibleProjectsDescription: 'Projetos disponíveis para o seu perfil.',
        creationTrend: 'Evolução das criações',
        creationTrendDescription: 'Comparativo de novos projetos e personas em {{period}}.',
        creationTrendTable: 'Dados detalhados da evolução de projetos e personas.',
        noCreationData: 'Ainda não há criações neste período.',
        activity: 'Atividade recente',
        noActivity: 'Nenhuma atividade recente',
        noActivityDescription: 'As próximas alterações realizadas na conta aparecerão aqui.',
        quickActions: 'Ações rápidas',
        reviewAccess: 'Revisar solicitações de acesso',
        createProject: 'Novo projeto',
        manageUsers: 'Gerenciar usuários'
      },
      preferences: {
        menu: 'Preferências', title: 'Preferências', description: 'Gerencie sua foto de perfil e a segurança da sua conta.',
        profileTitle: 'Foto de perfil', profileDescription: 'Esta foto identifica sua conta em toda a plataforma.', photoAlt: 'Foto de perfil de {{name}}', choosePhoto: 'Escolher foto', changePhoto: 'Trocar foto', removePhoto: 'Remover foto', photoHint: 'PNG ou JPEG, até 700 KB e 4096 × 4096 pixels.', invalidPhotoType: 'Use uma imagem PNG ou JPEG.', photoTooLarge: 'A imagem deve ter no máximo 700 KB.', photoUpdated: 'Foto de perfil atualizada.', photoRemoved: 'Foto de perfil removida.', photoError: 'Não foi possível atualizar a foto. Confira o arquivo e tente novamente.', photoRemoveError: 'Não foi possível remover a foto. Tente novamente.',
        passwordTitle: 'Alterar senha', passwordDescription: 'Confirme sua senha atual. Depois da alteração, você precisará entrar novamente.', currentPassword: 'Senha atual', currentPasswordRequired: 'Informe a senha atual.', newPassword: 'Nova senha', confirmNewPassword: 'Confirmar nova senha', confirmPasswordRequired: 'Confirme a nova senha.', passwordHint: 'Use 12 ou mais caracteres, com maiúscula, minúscula, número e símbolo.', passwordMismatch: 'As novas senhas não coincidem.', changePassword: 'Alterar senha', passwordUpdated: 'Senha alterada. Entre novamente com a nova senha.', currentPasswordInvalid: 'A senha atual está incorreta.', passwordError: 'Não foi possível alterar a senha. Revise os dados e tente novamente.'
      },
      tenants: {
        title: 'Organizações', description: 'Gerencie organizações isoladas, seus workspaces e acessos.', create: 'Adicionar organização', search: 'Buscar por nome ou identificador', empty: 'Nenhuma organização cadastrada', emptyDescription: 'Crie a primeira organização com administrador e workspace padrão.', manage: 'Gerenciar', columns: { tenant: 'Organização', workspaces: 'Workspaces', admins: 'Administradores', projects: 'Projetos', created: 'Criação' }
      },
      admins: {
        title: 'Administradores', description: 'Controle quem administra cada organização.', create: 'Criar administrador', search: 'Buscar por nome ou e-mail', empty: 'Nenhum administrador encontrado', emptyDescription: 'Crie um administrador e associe-o a uma única organização.', columns: { admin: 'Administrador', tenant: 'Organização', status: 'Status', created: 'Criação' }
      },
      projects: {
        title: 'Projetos', description: 'Organize pesquisas, personas e participantes em projetos exclusivos de um workspace.', create: 'Novo projeto', search: 'Buscar projetos', empty: 'Nenhum projeto criado', emptyDescription: 'Crie um projeto dentro de um workspace para começar.', memberCount: '{{count}} pessoas', open: 'Permissões', active: 'Em andamento', noDescription: 'Sem descrição.', inWorkspace: 'Workspace: {{name}}'
      },
      users: {
        title: 'Usuários', description: 'Gerencie identidades e vínculos independentes por organização e workspace.', membershipDescription: 'Vincule identidades existentes e delegue papéis sem duplicar usuários.', add: 'Adicionar vínculo', search: 'Buscar por nome ou e-mail', empty: 'Nenhum usuário encontrado', emptyClientDescription: 'Vincule uma identidade existente a esta organização.', emptyWorkspaceDescription: 'Adicione ao workspace uma pessoa já vinculada à organização.', addClientTitle: 'Vincular usuário à organização', addClientDescription: 'A identidade permanece única e recebe acesso somente nesta organização.', addWorkspaceTitle: 'Adicionar usuário ao workspace', addWorkspaceDescription: 'O usuário deve possuir vínculo ativo com a organização principal.', userIdentifier: 'ID do usuário', userIdentifierHint: 'Use o identificador da identidade global.', selectUser: 'Selecione um usuário', selectUserHint: 'São exibidos apenas usuários ativos da organização que ainda não participam deste workspace.', emailHint: 'Informe o e-mail exato de uma identidade já cadastrada.', initialPermissions: 'Permissões iniciais', initialPermissionsDescription: 'Estes padrões serão herdados por todos os projetos do workspace.', configurePermissions: 'Configurar permissões', makeClientAdmin: 'Tornar administrador da organização', makeWorkspaceAdmin: 'Tornar administrador do workspace', makeMember: 'Tornar membro', updated: 'Vínculo atualizado.', removed: 'Vínculo removido e histórico preservado.', removeTitle: 'Remover vínculo de {{name}}?', removeDescription: 'O acesso será encerrado neste escopo. Outros vínculos e o histórico serão preservados.', invite: 'Convidar usuário', projectAccess: '{{count}} projetos', columns: { user: 'Usuário', projects: 'Acesso a projetos', status: 'Status', created: 'Criação' }
      },
      permissions: {
        title: 'Permissões', functionalTitle: 'Permissões funcionais', description: 'Defina o nível de acesso de cada pessoa em cada projeto.', functionalDescription: 'Configure padrões do workspace e sobrescritas explícitas por projeto.', scopeTitle: 'Escopo da permissão', scope: 'Aplicação', workspaceDefaults: 'Padrões do workspace', projectOverride: 'Sobrescrita · {{name}}', user: 'Usuário', selectUser: 'Selecione um usuário', selectUserHint: 'Escolha uma pessoa para editar sua matriz funcional.', noMembers: 'Nenhum participante neste escopo', noMembersDescription: 'Adicione usuários ao workspace ou projeto antes de configurar seus acessos.', denyPriority: 'Negação explícita sempre prevalece sobre permissões herdadas. Alterações têm efeito nas próximas requisições.', saved: 'Permissões atualizadas.', saveError: 'Não foi possível salvar as permissões.', effect: 'Regra', level: 'Nível', allow: 'Permitir', deny: 'Negar', inherit: 'Herdar do workspace', effective: 'Efetivo: {{level}}', levels: { READ: 'Leitura', WRITE: 'Escrita', ADMIN: 'Administração' }, features: { PERSONA: { label: 'Personas', description: 'Criar, editar e visualizar personas.' }, RESEARCH: { label: 'Pesquisa', description: 'Criar, editar e visualizar questionários.' }, SIMULATION: { label: 'Simulação', description: 'Executar e visualizar salas de simulação.' }, DASHBOARD: { label: 'Dashboard', description: 'Acessar análises e relatórios.' } }, permission: { VIEWER: 'Leitor', CONTRIBUTOR: 'Colaborador', MANAGER: 'Gestor', OWNER: 'Responsável' }, permissionHint: { VIEWER: 'Consulta o projeto e as personas.', CONTRIBUTOR: 'Também cria e edita personas.', MANAGER: 'Também gerencia participantes e configurações.', OWNER: 'Controle completo do projeto.' }
      },
      workspaces: { title: 'Workspaces', description: 'Separe projetos, equipes e associações de ativos dentro da organização.', create: 'Novo workspace', search: 'Buscar workspaces', empty: 'Nenhum workspace criado', emptyDescription: 'Crie um workspace adicional para organizar projetos e equipes.', default: 'Padrão', noDescription: 'Sem descrição.', projectCount: '{{count}} projetos', memberCount: '{{count}} pessoas', open: 'Abrir', deleted: 'Workspace excluído.', deleteTitle: 'Excluir {{name}}?', deleteDescription: 'A exclusão será bloqueada se violar vínculos, projetos ou a regra do último administrador.' },
      assets: { associationsSaved: 'Associações atualizadas.', associateTitle: 'Workspaces com acesso a {{name}}', associateDescription: 'A associação é por referência. Editar o ativo refletirá em todos os workspaces selecionados.' },
      personas: { title: 'Personas', description: 'Gerencie personas uma única vez na organização e compartilhe-as por referência.', create: 'Nova persona', createTitle: 'Criar persona', createDescription: 'A persona será criada na organização e poderá ser associada a vários workspaces.', editTitle: 'Editar {{name}}', editDescription: 'As alterações serão refletidas imediatamente em todos os workspaces associados.', search: 'Buscar personas', empty: 'Nenhuma persona criada', emptyDescription: 'Crie a primeira persona desta organização.', emptyWorkspaceDescription: 'Nenhuma persona está associada a este workspace.', noDescription: 'Sem descrição.', notAssociated: 'Sem workspace associado', manageAssociations: 'Gerenciar associações', inUse: 'Em uso em {{count}} projetos', updated: 'Persona atualizada.', deleted: 'Persona excluída.', deleteTitle: 'Excluir {{name}} da organização?', deleteDescription: 'A persona será removida de todos os workspaces. Snapshots históricos permanecem.', deleteBlocked: 'Esta persona está em uso por projetos ativos e não pode ser excluída.' },
      questionnaires: { title: 'Questionários', description: 'Gerencie questionários uma única vez na organização e compartilhe-os por referência.', create: 'Novo questionário', createTitle: 'Criar questionário', createDescription: 'O questionário será criado na organização e poderá ser associado a vários workspaces.', editTitle: 'Editar {{name}}', editDescription: 'As alterações serão refletidas imediatamente em todos os workspaces associados.', search: 'Buscar questionários', empty: 'Nenhum questionário criado', emptyDescription: 'Crie o primeiro questionário desta organização.', emptyWorkspaceDescription: 'Nenhum questionário está associado a este workspace.', noDescription: 'Sem descrição.', notAssociated: 'Sem workspace associado', manageAssociations: 'Gerenciar associações', inUse: 'Em uso em {{count}} projetos', updated: 'Questionário atualizado.', deleted: 'Questionário excluído.', deleteTitle: 'Excluir {{name}} da organização?', deleteDescription: 'O questionário será removido de todos os workspaces. Snapshots históricos permanecem.', deleteBlocked: 'Este questionário está em uso por projetos ativos e não pode ser excluído.' },
      forbidden: { title: 'Você não tem acesso a esta área', description: 'Seu perfil não possui a permissão necessária. Se isso parecer incorreto, fale com o administrador da conta.' },
      roles: { SUPER_ADMIN: 'Superadministrador', CLIENT_ADMIN: 'Administrador da organização', CLIENT_MEMBER: 'Membro da organização', WORKSPACE_ADMIN: 'Administrador do workspace', WORKSPACE_MEMBER: 'Membro do workspace', PROJECT_USER: 'Usuário de projeto' },
    },
  },
  es: {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Cargando', retry: 'Intentar de nuevo', cancel: 'Cancelar', save: 'Guardar cambios', create: 'Crear', delete: 'Eliminar', remove: 'Quitar', search: 'Buscar', actions: 'Acciones', status: 'Estado', pending: 'Pendiente', pending_approval: 'Pendiente de aprobación', active: 'Activo', invited: 'Invitado', suspended: 'Suspendido', removed: 'Eliminado', archived: 'Archivado', openMenu: 'Abrir menú', expandSidebar: 'Expandir barra lateral', collapseSidebar: 'Contraer barra lateral', close: 'Cerrar', previous: 'Anterior', next: 'Siguiente', page: 'Página {{current}} de {{total}}', noResults: 'Sin resultados', edit: 'Editar', unknown: 'No informado', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Oscuro', system: 'Sistema', signOut: 'Salir', account: 'Cuenta', menu: 'Menú', email: 'Correo', password: 'Contraseña', name: 'Nombre', tenant: 'Organización', workspace: 'Workspace', members: 'personas', projects: 'proyectos', updatedAt: 'Actualizado el', createdAt: 'Creado el', permissions: 'Permisos', accessDenied: 'Acceso denegado', backHome: 'Volver al resumen', notFound: 'Página no encontrada', notFoundDescription: 'La dirección puede haber cambiado o no existir.', errorTitle: 'No se pudo cargar', errorDescription: 'Comprueba tu conexión e inténtalo de nuevo.'
      },
      auth: { title: 'Bienvenido de nuevo', subtitle: 'Administra organizaciones, proyectos y permisos con seguridad.', brandKicker: 'Personas creadas con contexto', brandStatement: 'Crea personas consistentes para responder investigaciones con mayor claridad.', emailPlaceholder: 'tu@empresa.com', passwordPlaceholder: 'Tu contraseña', showPassword: 'Mostrar contraseña', hidePassword: 'Ocultar contraseña', rememberMe: 'Recordarme en este dispositivo', submit: 'Entrar', submitting: 'Entrando…', invalidCredentials: 'Correo o contraseña incorrectos.', pendingApproval: 'Tu registro aún espera la aprobación de un administrador.', inactiveAccount: 'Tu cuenta está inactiva. Contacta a un administrador.', genericError: 'No se pudo iniciar sesión. Inténtalo de nuevo.', secureSession: 'Tu sesión está protegida por una cookie segura. La contraseña nunca se guarda en este dispositivo.', expired: 'Tu sesión expiró. Inicia sesión nuevamente.' },
      authCarousel: { label: 'Funciones de PersonaIA', controls: 'Controles del carrusel', pause: 'Pausar presentación', play: 'Continuar presentación', goToSlide: 'Ver diapositiva {{number}}: {{title}}', researchTitle: 'Comprende lo que las personas realmente expresan', researchDescription: 'Organiza respuestas y convierte señales dispersas en contexto útil para tu investigación.', personasTitle: 'Crea personas consistentes en minutos', personasDescription: 'Modela perfiles genéricos con motivaciones, comportamientos y lenguaje alineados con tu objetivo.', decisionsTitle: 'Lleva insights claros a cada decisión', decisionsDescription: 'Compara perspectivas, refina hipótesis y mantén proyectos y equipos dentro del mismo contexto.', simulationTitle: 'Anticipa respuestas antes del trabajo de campo', simulationDescription: 'Simula cómo distintos perfiles pueden responder al cuestionario y refina hipótesis con mayor confianza.', governanceTitle: 'Mantén cada proyecto en el contexto correcto', governanceDescription: 'Organiza personas, equipos y permisos por organización sin mezclar datos ni responsabilidades.' },
      registration: { eyebrow: 'Nuevo acceso', title: 'Te damos la bienvenida', subtitle: 'Introduce el código de tu organización. El acceso se habilitará tras la aprobación de un administrador.', namePlaceholder: 'Tu nombre completo', emailPlaceholder: 'tu@empresa.com', tenantPlaceholder: 'empresa-ejemplo', tenantCode: 'Código de la organización', tenantHint: 'Solicita este código al administrador de tu organización.', confirmPassword: 'Confirmar contraseña', confirmPasswordPlaceholder: 'Repite tu contraseña', passwordMismatch: 'Las contraseñas no coinciden.', submit: 'Solicitar registro', submitting: 'Enviando…', requestSent: 'Solicitud de registro enviada.', successTitle: 'Registro pendiente de aprobación', successDescription: 'Recibimos tus datos. Podrás entrar cuando un administrador apruebe y active tu cuenta.', backToLogin: 'Volver al inicio de sesión', alreadyHaveAccount: '¿Ya tienes una cuenta?', noAccount: '¿Aún no tienes acceso?', createAccount: 'Crear cuenta', invalidTenant: 'El código de la organización es inválido o está inactivo.' },
      validation: { required: 'Campo obligatorio.', email: 'Introduce un correo válido.', passwordLength: 'Usa al menos 8 caracteres.' },
      forms: {
        error: 'No se pudo completar. Revisa los datos e inténtalo de nuevo.', created: 'Registro completado correctamente.', moved: 'Usuario movido al nuevo proyecto.', tenantName: 'Nombre de la organización', slug: 'Identificador', segment: 'Segmento', initialAdmin: 'Administrador inicial', passwordHint: 'Usa 12 o más caracteres, con mayúscula, minúscula, número y símbolo.', description: 'Descripción', projects: 'Proyectos iniciales', projectsHint: 'Opcional. Podrás cambiar los proyectos después.', initialPermission: 'Permiso inicial', selectTenant: 'Selecciona una organización', selectWorkspace: 'Selecciona un workspace', selectProject: 'Selecciona un proyecto', fromProject: 'Proyecto de origen', toProject: 'Proyecto de destino', moveUser: 'Mover entre proyectos', createTenantTitle: 'Nueva organización y administrador', createTenantDescription: 'La organización se creará con su primer administrador y un workspace predeterminado.', createWorkspaceTitle: 'Nuevo workspace', createWorkspaceDescription: 'Organiza proyectos y accesos en un espacio exclusivo de la organización.', createAdminTitle: 'Nuevo administrador', createAdminDescription: 'El administrador solo tendrá acceso a la organización seleccionada.', createProjectTitle: 'Nuevo proyecto', createProjectDescription: 'El proyecto quedará vinculado permanentemente al workspace seleccionado.', createUserTitle: 'Nuevo usuario', createUserDescription: 'Registra a la persona y asigna proyectos y un preset de permisos.', moveUserTitle: 'Mover a {{name}}', moveUserDescription: 'El acceso se eliminará del proyecto de origen y se creará en el destino.', validation: { name: 'Usa al menos 2 caracteres.', slug: 'Usa solo minúsculas, números y guiones.', password: 'La contraseña no cumple los requisitos de seguridad.', tenant: 'Selecciona una organización.', workspace: 'Selecciona un workspace.', user: 'Introduce la identidad del usuario.', differentProject: 'Elige un proyecto diferente al de origen.' }
      },
      notifications: { title: 'Notificaciones', titleWithUnread: 'Notificaciones, {{count}} no leídas', empty: 'Todo al día', emptyDescription: 'Las nuevas actividades importantes aparecerán aquí.', markAllRead: 'Marcar todas como leídas', loading: 'Cargando notificaciones', loadError: 'No se pudieron cargar las notificaciones.', updateError: 'No se pudo actualizar la notificación.', unread: 'No leída', resolved: 'Solicitud resuelta', accessRequestedTitle: 'Nueva solicitud de acceso', accessRequestedDescription: '{{userName}} ({{userEmail}}) solicitó acceso a {{tenantName}}.', newActivity: 'Nueva actividad', newActivityDescription: 'Hay una nueva actualización para revisar.' },
      nav: { platform: 'Plataforma', organization: 'Organización', overview: 'Resumen', accessControl: 'Control de accesos', tenants: 'Organizaciones', admins: 'Administradores', workspaces: 'Workspaces', projects: 'Proyectos', users: 'Usuarios', permissions: 'Permisos', personas: 'Personas', questionnaires: 'Cuestionarios' },
      context: { scope: 'Contexto de trabajo', client: 'Organización', workspace: 'Workspace', selectClient: 'Selecciona una organización', selectClientDescription: 'Elige la organización para consultar sus datos aislados.', selectWorkspace: 'Selecciona un workspace', selectWorkspaceDescription: 'Elige el workspace para configurar accesos y permisos.', allWorkspaces: 'Todos los workspaces' },
      accessControl: { title: 'Control de accesos', superDescription: 'Aprueba registros por organización y administra identidades globales en áreas separadas.', clientDescription: 'Aprueba y gestiona usuarios comunes de tu propia organización.', viewLabel: 'Tipo de control de acceso', clientAccess: 'Acceso de la organización', platformIdentities: 'Identidades de la plataforma', platformEmptyDescription: 'Las identidades globales registradas aparecerán aquí.', membershipCount: '{{count}} vínculos con organizaciones', globalRole: 'Rol global', standardIdentity: 'Identidad estándar', defaultClient: 'Organización predeterminada', editPlatformTitle: 'Acceso global de {{name}}', editPlatformDescription: 'Esta área solo cambia el rol y el estado global de la identidad.', search: 'Buscar por nombre o correo', filterLabel: 'Filtrar usuarios por estado', filters: { ALL: 'Todos', PENDING: 'Pendientes', ACTIVE: 'Activos', SUSPENDED: 'Inactivos', ARCHIVED: 'Rechazados' }, empty: 'No hay usuarios en este filtro', emptyDescription: 'Las nuevas solicitudes y cuentas gestionables aparecerán aquí.', role: 'Perfil de acceso en la organización', platform: 'Plataforma', you: '(tú)', approve: 'Aprobar', reject: 'Rechazar', activate: 'Activar', deactivate: 'Desactivar', editAccess: 'Cambiar acceso', editTitle: 'Acceso de {{name}}', editDescription: 'Este cambio solo se aplica a la organización seleccionada.', approved: 'Registro aprobado y acceso habilitado.', rejected: 'Registro rechazado.', updated: 'Acceso actualizado.', securityWarning: 'Los roles y estados solo se aplican a esta organización. Los demás vínculos de identidad se conservan.', platformSecurityWarning: 'Los cambios globales cierran las sesiones abiertas. Los vínculos por organización permanecen separados y deben administrarse en el área de acceso de la organización.' },
      dashboard: { title: 'Resumen', superDescription: 'Supervisa los indicadores globales, la creación de proyectos y personas y las solicitudes de acceso de la plataforma.', clientDescription: 'Supervisa los indicadores, proyectos, personas y accesos de tu organización.', userDescription: 'Consulta los proyectos a los que se habilitó tu acceso.', periodFilter: 'Período de los datos', ranges: { '7d': '7 días', '30d': '30 días', '12m': '12 meses', '5y': '5 años' }, keyIndicators: 'Indicadores principales', projectsCreated: 'Proyectos creados', personasCreated: 'Personas creadas', activeUsers: 'Usuarios activos', pendingAccessRequests: 'Solicitudes pendientes', createdInPeriod: 'Total en el período seleccionado: {{period}}.', activeUsersDescription: 'Cuentas con acceso activo en este momento.', pendingAccessRequestsDescription: 'Solicitudes que aún necesitan la decisión de un administrador.', accessibleProjects: 'Proyectos con acceso', accessibleProjectsDescription: 'Proyectos disponibles para tu perfil.', creationTrend: 'Evolución de las creaciones', creationTrendDescription: 'Comparación de nuevos proyectos y personas en {{period}}.', creationTrendTable: 'Datos detallados de la evolución de proyectos y personas.', noCreationData: 'Todavía no hay creaciones en este período.', activity: 'Actividad reciente', noActivity: 'Sin actividad reciente', noActivityDescription: 'Los próximos cambios aparecerán aquí.', quickActions: 'Acciones rápidas', reviewAccess: 'Revisar solicitudes de acceso', createProject: 'Nuevo proyecto', manageUsers: 'Gestionar usuarios' },
      preferences: {
        menu: 'Preferencias', title: 'Preferencias', description: 'Gestiona tu foto de perfil y la seguridad de tu cuenta.',
        profileTitle: 'Foto de perfil', profileDescription: 'Esta foto identifica tu cuenta en toda la plataforma.', photoAlt: 'Foto de perfil de {{name}}', choosePhoto: 'Elegir foto', changePhoto: 'Cambiar foto', removePhoto: 'Eliminar foto', photoHint: 'PNG o JPEG, hasta 700 KB y 4096 × 4096 píxeles.', invalidPhotoType: 'Usa una imagen PNG o JPEG.', photoTooLarge: 'La imagen debe tener como máximo 700 KB.', photoUpdated: 'Foto de perfil actualizada.', photoRemoved: 'Foto de perfil eliminada.', photoError: 'No se pudo actualizar la foto. Comprueba el archivo e inténtalo de nuevo.', photoRemoveError: 'No se pudo eliminar la foto. Inténtalo de nuevo.',
        passwordTitle: 'Cambiar contraseña', passwordDescription: 'Confirma tu contraseña actual. Después del cambio, tendrás que iniciar sesión de nuevo.', currentPassword: 'Contraseña actual', currentPasswordRequired: 'Introduce la contraseña actual.', newPassword: 'Nueva contraseña', confirmNewPassword: 'Confirmar nueva contraseña', confirmPasswordRequired: 'Confirma la nueva contraseña.', passwordHint: 'Usa 12 o más caracteres, con mayúscula, minúscula, número y símbolo.', passwordMismatch: 'Las nuevas contraseñas no coinciden.', changePassword: 'Cambiar contraseña', passwordUpdated: 'Contraseña actualizada. Inicia sesión de nuevo con la nueva contraseña.', currentPasswordInvalid: 'La contraseña actual es incorrecta.', passwordError: 'No se pudo cambiar la contraseña. Revisa los datos e inténtalo de nuevo.'
      },
      tenants: { title: 'Organizaciones', description: 'Gestiona organizaciones aisladas, sus workspaces y accesos.', create: 'Añadir organización', search: 'Buscar por nombre o identificador', empty: 'No hay organizaciones', emptyDescription: 'Crea la primera organización con administrador y workspace predeterminado.', manage: 'Gestionar', columns: { tenant: 'Organización', workspaces: 'Workspaces', admins: 'Administradores', projects: 'Proyectos', created: 'Creación' } },
      admins: { title: 'Administradores', description: 'Controla quién administra cada organización.', create: 'Crear administrador', search: 'Buscar por nombre o correo', empty: 'No hay administradores', emptyDescription: 'Crea un administrador y asígnalo a una única organización.', columns: { admin: 'Administrador', tenant: 'Organización', status: 'Estado', created: 'Creación' } },
      projects: { title: 'Proyectos', description: 'Organiza investigaciones, personas y participantes en proyectos exclusivos de un workspace.', create: 'Nuevo proyecto', search: 'Buscar proyectos', empty: 'No hay proyectos', emptyDescription: 'Crea un proyecto dentro de un workspace para comenzar.', memberCount: '{{count}} personas', open: 'Permisos', active: 'En curso', noDescription: 'Sin descripción.', inWorkspace: 'Workspace: {{name}}' },
      users: { title: 'Usuarios', description: 'Gestiona usuarios y vínculos.', membershipDescription: 'Vincula identidades existentes y delega roles sin duplicar usuarios.', add: 'Añadir vínculo', search: 'Buscar por nombre o correo', empty: 'No hay usuarios', emptyClientDescription: 'Vincula una identidad existente a esta organización.', emptyWorkspaceDescription: 'Añade al workspace una persona ya vinculada a la organización.', addClientTitle: 'Vincular usuario a la organización', addClientDescription: 'La identidad sigue siendo única y recibe acceso solo en esta organización.', addWorkspaceTitle: 'Añadir usuario al workspace', addWorkspaceDescription: 'El usuario debe tener un vínculo activo con la organización principal.', userIdentifier: 'ID del usuario', userIdentifierHint: 'Usa el identificador de la identidad global.', selectUser: 'Selecciona un usuario', selectUserHint: 'Solo se muestran usuarios activos de la organización que aún no están en este workspace.', emailHint: 'Introduce el correo exacto de una identidad ya registrada.', initialPermissions: 'Permisos iniciales', initialPermissionsDescription: 'Estos valores serán heredados por todos los proyectos del workspace.', configurePermissions: 'Configurar permisos', makeClientAdmin: 'Hacer administrador de la organización', makeWorkspaceAdmin: 'Hacer administrador del workspace', makeMember: 'Hacer miembro', updated: 'Vínculo actualizado.', removed: 'Vínculo eliminado y el historial preservado.', removeTitle: '¿Quitar el vínculo de {{name}}?', removeDescription: 'El acceso terminará en este alcance. Los demás vínculos y el historial se conservarán.', invite: 'Invitar usuario', projectAccess: '{{count}} proyectos', columns: { user: 'Usuario', projects: 'Acceso a proyectos', status: 'Estado', created: 'Creación' } },
      permissions: { title: 'Permisos', functionalTitle: 'Permisos funcionales', description: 'Define el nivel de acceso.', functionalDescription: 'Configura valores predeterminados del workspace y sobrescrituras explícitas por proyecto.', scopeTitle: 'Alcance del permiso', scope: 'Aplicación', workspaceDefaults: 'Valores del workspace', projectOverride: 'Sobrescritura · {{name}}', user: 'Usuario', selectUser: 'Selecciona un usuario', selectUserHint: 'Elige una persona para editar su matriz funcional.', noMembers: 'No hay participantes en este alcance', noMembersDescription: 'Añade usuarios antes de configurar sus accesos.', denyPriority: 'La denegación explícita siempre prevalece sobre los permisos heredados. Los cambios se aplican en las siguientes solicitudes.', saved: 'Permisos actualizados.', saveError: 'No se pudieron guardar los permisos.', effect: 'Regla', level: 'Nivel', allow: 'Permitir', deny: 'Denegar', inherit: 'Heredar del workspace', effective: 'Efectivo: {{level}}', levels: { READ: 'Lectura', WRITE: 'Escritura', ADMIN: 'Administración' }, features: { PERSONA: { label: 'Personas', description: 'Crear, editar y visualizar personas.' }, RESEARCH: { label: 'Investigación', description: 'Crear, editar y visualizar cuestionarios.' }, SIMULATION: { label: 'Simulación', description: 'Ejecutar y visualizar salas de simulación.' }, DASHBOARD: { label: 'Dashboard', description: 'Acceder a análisis e informes.' } }, permission: { VIEWER: 'Lector', CONTRIBUTOR: 'Colaborador', MANAGER: 'Gestor', OWNER: 'Responsable' }, permissionHint: { VIEWER: 'Consulta el proyecto y las personas.', CONTRIBUTOR: 'También crea y edita personas.', MANAGER: 'También gestiona participantes y ajustes.', OWNER: 'Control completo del proyecto.' } },
      workspaces: { title: 'Workspaces', description: 'Separa proyectos, equipos y asociaciones de activos dentro de la organización.', create: 'Nuevo workspace', search: 'Buscar workspaces', empty: 'No hay workspaces', emptyDescription: 'Crea un workspace adicional para organizar proyectos y equipos.', default: 'Predeterminado', noDescription: 'Sin descripción.', projectCount: '{{count}} proyectos', memberCount: '{{count}} personas', open: 'Abrir', deleted: 'Workspace eliminado.', deleteTitle: '¿Eliminar {{name}}?', deleteDescription: 'La eliminación se bloqueará si viola vínculos, proyectos o la regla del último administrador.' },
      assets: { associationsSaved: 'Asociaciones actualizadas.', associateTitle: 'Workspaces con acceso a {{name}}', associateDescription: 'La asociación es por referencia. Editar el activo se reflejará en todos los workspaces seleccionados.' },
      personas: { title: 'Personas', description: 'Gestiona personas una sola vez en la organización y compártelas por referencia.', create: 'Nueva persona', createTitle: 'Crear persona', createDescription: 'La persona se creará en la organización y podrá asociarse a varios workspaces.', editTitle: 'Editar {{name}}', editDescription: 'Los cambios se reflejarán inmediatamente en todos los workspaces asociados.', search: 'Buscar personas', empty: 'No hay personas', emptyDescription: 'Crea la primera persona de esta organización.', emptyWorkspaceDescription: 'Ninguna persona está asociada a este workspace.', noDescription: 'Sin descripción.', notAssociated: 'Sin workspace asociado', manageAssociations: 'Gestionar asociaciones', inUse: 'En uso en {{count}} proyectos', updated: 'Persona actualizada.', deleted: 'Persona eliminada.', deleteTitle: '¿Eliminar {{name}} de la organización?', deleteDescription: 'La persona se quitará de todos los workspaces. Las capturas históricas permanecen.', deleteBlocked: 'Esta persona está en uso por proyectos activos y no puede eliminarse.' },
      questionnaires: { title: 'Cuestionarios', description: 'Gestiona cuestionarios una sola vez en la organización y compártelos por referencia.', create: 'Nuevo cuestionario', createTitle: 'Crear cuestionario', createDescription: 'El cuestionario se creará en la organización y podrá asociarse a varios workspaces.', editTitle: 'Editar {{name}}', editDescription: 'Los cambios se reflejarán inmediatamente en todos los workspaces asociados.', search: 'Buscar cuestionarios', empty: 'No hay cuestionarios', emptyDescription: 'Crea el primer cuestionario de esta organización.', emptyWorkspaceDescription: 'Ningún cuestionario está asociado a este workspace.', noDescription: 'Sin descripción.', notAssociated: 'Sin workspace asociado', manageAssociations: 'Gestionar asociaciones', inUse: 'En uso en {{count}} proyectos', updated: 'Cuestionario actualizado.', deleted: 'Cuestionario eliminado.', deleteTitle: '¿Eliminar {{name}} de la organización?', deleteDescription: 'El cuestionario se quitará de todos los workspaces. Las capturas históricas permanecen.', deleteBlocked: 'Este cuestionario está en uso por proyectos activos y no puede eliminarse.' },
      forbidden: { title: 'No tienes acceso a esta área', description: 'Tu perfil no tiene el permiso necesario. Contacta al administrador si crees que es un error.' },
      roles: { SUPER_ADMIN: 'Superadministrador', CLIENT_ADMIN: 'Administrador de la organización', CLIENT_MEMBER: 'Miembro de la organización', WORKSPACE_ADMIN: 'Administrador del workspace', WORKSPACE_MEMBER: 'Miembro del workspace', PROJECT_USER: 'Usuario de proyecto' },
    },
  },
  en: {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Loading', retry: 'Try again', cancel: 'Cancel', save: 'Save changes', create: 'Create', delete: 'Delete', remove: 'Remove', search: 'Search', actions: 'Actions', status: 'Status', pending: 'Pending', pending_approval: 'Awaiting approval', active: 'Active', invited: 'Invited', suspended: 'Suspended', removed: 'Removed', archived: 'Archived', openMenu: 'Open menu', expandSidebar: 'Expand sidebar', collapseSidebar: 'Collapse sidebar', close: 'Close', previous: 'Previous', next: 'Next', page: 'Page {{current}} of {{total}}', noResults: 'No results', edit: 'Edit', unknown: 'Not provided', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', system: 'System', signOut: 'Sign out', account: 'Account', menu: 'Menu', email: 'Email', password: 'Password', name: 'Name', tenant: 'Organization', workspace: 'Workspace', members: 'people', projects: 'projects', updatedAt: 'Updated', createdAt: 'Created', permissions: 'Permissions', accessDenied: 'Access denied', backHome: 'Back to overview', notFound: 'Page not found', notFoundDescription: 'This address may have changed or does not exist.', errorTitle: 'Unable to load', errorDescription: 'Check your connection and try again.'
      },
      auth: { title: 'Welcome back', subtitle: 'Manage organizations, projects, and permissions securely.', brandKicker: 'Personas built with context', brandStatement: 'Create consistent personas to answer research with greater clarity.', emailPlaceholder: 'you@company.com', passwordPlaceholder: 'Your password', showPassword: 'Show password', hidePassword: 'Hide password', rememberMe: 'Remember me on this device', submit: 'Sign in', submitting: 'Signing in…', invalidCredentials: 'Incorrect email or password.', pendingApproval: 'Your registration is still awaiting administrator approval.', inactiveAccount: 'Your account is inactive. Contact an administrator.', genericError: 'Unable to sign in right now. Try again.', secureSession: 'Your session is protected by a secure cookie. Your password is never saved on this device.', expired: 'Your session expired. Sign in again.' },
      authCarousel: { label: 'PersonaIA capabilities', controls: 'Carousel controls', pause: 'Pause presentation', play: 'Continue presentation', goToSlide: 'View slide {{number}}: {{title}}', researchTitle: 'Understand what people are really saying', researchDescription: 'Organize responses and turn scattered signals into useful context for your research.', personasTitle: 'Create consistent personas in minutes', personasDescription: 'Model generic profiles with motivations, behaviors, and language aligned with your objective.', decisionsTitle: 'Bring clear insights to every decision', decisionsDescription: 'Compare perspectives, refine hypotheses, and keep projects and teams working from the same context.', simulationTitle: 'Anticipate responses before fieldwork', simulationDescription: 'Simulate how different profiles may answer a questionnaire and refine hypotheses with greater confidence.', governanceTitle: 'Keep every project in the right context', governanceDescription: 'Organize personas, teams, and permissions by organization without mixing data or responsibilities.' },
      registration: { eyebrow: 'New access', title: 'Welcome', subtitle: 'Enter your organization code. Access will be enabled after an administrator approves it.', namePlaceholder: 'Your full name', emailPlaceholder: 'you@company.com', tenantPlaceholder: 'company-example', tenantCode: 'Organization code', tenantHint: 'Ask your organization administrator for this code.', confirmPassword: 'Confirm password', confirmPasswordPlaceholder: 'Repeat your password', passwordMismatch: 'Passwords do not match.', submit: 'Request registration', submitting: 'Submitting…', requestSent: 'Registration request submitted.', successTitle: 'Registration awaiting approval', successDescription: 'We received your details. You can sign in after an administrator approves and activates your account.', backToLogin: 'Back to sign in', alreadyHaveAccount: 'Already have an account?', noAccount: 'Do not have access yet?', createAccount: 'Create account', invalidTenant: 'The organization code is invalid or inactive.' },
      validation: { required: 'Required field.', email: 'Enter a valid email.', passwordLength: 'Use at least 8 characters.' },
      forms: {
        error: 'Unable to complete this action. Review the data and try again.', created: 'Successfully created.', moved: 'User moved to the new project.', tenantName: 'Organization name', slug: 'Identifier', segment: 'Segment', initialAdmin: 'Initial administrator', passwordHint: 'Use 12 or more characters with uppercase, lowercase, a number, and a symbol.', description: 'Description', projects: 'Initial projects', projectsHint: 'Optional. You can change project access later.', initialPermission: 'Initial permission', selectTenant: 'Select an organization', selectWorkspace: 'Select a workspace', selectProject: 'Select a project', fromProject: 'Source project', toProject: 'Destination project', moveUser: 'Move between projects', createTenantTitle: 'New organization and administrator', createTenantDescription: 'The organization will be created with its first administrator and a default workspace.', createWorkspaceTitle: 'New workspace', createWorkspaceDescription: 'Organize projects and access in a workspace exclusive to the organization.', createAdminTitle: 'New administrator', createAdminDescription: 'The administrator will only have access to the selected organization.', createProjectTitle: 'New project', createProjectDescription: 'The project will remain permanently linked to the selected workspace.', createUserTitle: 'New user', createUserDescription: 'Register the person and optionally assign projects and a permission preset.', moveUserTitle: 'Move {{name}}', moveUserDescription: 'Access will be removed from the source project and created in the destination.', validation: { name: 'Use at least 2 characters.', slug: 'Use lowercase letters, numbers, and hyphens only.', password: 'The password does not meet the security requirements.', tenant: 'Select an organization.', workspace: 'Select a workspace.', user: 'Enter the user identity.', differentProject: 'Choose a project different from the source.' }
      },
      notifications: { title: 'Notifications', titleWithUnread: 'Notifications, {{count}} unread', empty: 'You are all caught up', emptyDescription: 'New important activity will appear here.', markAllRead: 'Mark all as read', loading: 'Loading notifications', loadError: 'Unable to load notifications.', updateError: 'Unable to update the notification.', unread: 'Unread', resolved: 'Request resolved', accessRequestedTitle: 'New access request', accessRequestedDescription: '{{userName}} ({{userEmail}}) requested access to {{tenantName}}.', newActivity: 'New activity', newActivityDescription: 'There is a new update to review.' },
      nav: { platform: 'Platform', organization: 'Organization', overview: 'Overview', accessControl: 'Access control', tenants: 'Organizations', admins: 'Administrators', workspaces: 'Workspaces', projects: 'Projects', users: 'Users', permissions: 'Permissions', personas: 'Personas', questionnaires: 'Questionnaires' },
      context: { scope: 'Working context', client: 'Organization', workspace: 'Workspace', selectClient: 'Select an organization', selectClientDescription: 'Choose the organization to view its isolated data.', selectWorkspace: 'Select a workspace', selectWorkspaceDescription: 'Choose the workspace to configure access and permissions.', allWorkspaces: 'All workspaces' },
      accessControl: { title: 'Access control', superDescription: 'Approve registrations by organization and manage global identities in separate areas.', clientDescription: 'Approve and manage standard users in your own organization.', viewLabel: 'Access control type', clientAccess: 'Organization access', platformIdentities: 'Platform identities', platformEmptyDescription: 'Registered global identities will appear here.', membershipCount: '{{count}} organization memberships', globalRole: 'Global role', standardIdentity: 'Standard identity', defaultClient: 'Default organization', editPlatformTitle: '{{name}} global access', editPlatformDescription: 'This area only changes the identity’s global role and status.', search: 'Search by name or email', filterLabel: 'Filter users by status', filters: { ALL: 'All', PENDING: 'Pending', ACTIVE: 'Active', SUSPENDED: 'Inactive', ARCHIVED: 'Rejected' }, empty: 'No users in this filter', emptyDescription: 'New registration requests and manageable accounts will appear here.', role: 'Organization access role', platform: 'Platform', you: '(you)', approve: 'Approve', reject: 'Reject', activate: 'Activate', deactivate: 'Deactivate', editAccess: 'Change access', editTitle: '{{name}} access', editDescription: 'This change only applies to the selected organization.', approved: 'Registration approved and access enabled.', rejected: 'Registration rejected.', updated: 'Access updated.', securityWarning: 'Roles and statuses only apply to this organization. The identity’s other memberships remain preserved.', platformSecurityWarning: 'Global changes close open sessions. Organization memberships remain separate and must be managed in the organization access area.' },
      dashboard: { title: 'Overview', superDescription: 'Monitor platform-wide indicators, project and persona creation, and access requests.', clientDescription: 'Monitor your organization’s indicators, projects, personas, and access.', userDescription: 'View the projects for which your access has been enabled.', periodFilter: 'Data period', ranges: { '7d': '7 days', '30d': '30 days', '12m': '12 months', '5y': '5 years' }, keyIndicators: 'Key indicators', projectsCreated: 'Projects created', personasCreated: 'Personas created', activeUsers: 'Active users', pendingAccessRequests: 'Pending access requests', createdInPeriod: 'Total in the selected period: {{period}}.', activeUsersDescription: 'Accounts with active access right now.', pendingAccessRequestsDescription: 'Requests that still need an administrator’s decision.', accessibleProjects: 'Accessible projects', accessibleProjectsDescription: 'Projects available to your account.', creationTrend: 'Creation trend', creationTrendDescription: 'New projects and personas compared across {{period}}.', creationTrendTable: 'Detailed project and persona creation trend data.', noCreationData: 'There are no creations in this period yet.', activity: 'Recent activity', noActivity: 'No recent activity', noActivityDescription: 'Upcoming account changes will appear here.', quickActions: 'Quick actions', reviewAccess: 'Review access requests', createProject: 'New project', manageUsers: 'Manage users' },
      preferences: {
        menu: 'Preferences', title: 'Preferences', description: 'Manage your profile photo and account security.',
        profileTitle: 'Profile photo', profileDescription: 'This photo identifies your account throughout the platform.', photoAlt: '{{name}} profile photo', choosePhoto: 'Choose photo', changePhoto: 'Change photo', removePhoto: 'Remove photo', photoHint: 'PNG or JPEG, up to 700 KB and 4096 × 4096 pixels.', invalidPhotoType: 'Use a PNG or JPEG image.', photoTooLarge: 'The image must be no larger than 700 KB.', photoUpdated: 'Profile photo updated.', photoRemoved: 'Profile photo removed.', photoError: 'Unable to update the photo. Check the file and try again.', photoRemoveError: 'Unable to remove the photo. Try again.',
        passwordTitle: 'Change password', passwordDescription: 'Confirm your current password. After the change, you will need to sign in again.', currentPassword: 'Current password', currentPasswordRequired: 'Enter your current password.', newPassword: 'New password', confirmNewPassword: 'Confirm new password', confirmPasswordRequired: 'Confirm the new password.', passwordHint: 'Use 12 or more characters with uppercase, lowercase, a number, and a symbol.', passwordMismatch: 'The new passwords do not match.', changePassword: 'Change password', passwordUpdated: 'Password changed. Sign in again with your new password.', currentPasswordInvalid: 'The current password is incorrect.', passwordError: 'Unable to change the password. Review the details and try again.'
      },
      tenants: { title: 'Organizations', description: 'Manage isolated organizations, their workspaces, and access.', create: 'Add organization', search: 'Search by name or identifier', empty: 'No organizations yet', emptyDescription: 'Create the first organization with an administrator and default workspace.', manage: 'Manage', columns: { tenant: 'Organization', workspaces: 'Workspaces', admins: 'Administrators', projects: 'Projects', created: 'Created' } },
      admins: { title: 'Administrators', description: 'Control who administers each organization.', create: 'Create administrator', search: 'Search by name or email', empty: 'No administrators found', emptyDescription: 'Create an administrator and assign them to one organization.', columns: { admin: 'Administrator', tenant: 'Organization', status: 'Status', created: 'Created' } },
      projects: { title: 'Projects', description: 'Organize research, personas, and participants in projects exclusive to one workspace.', create: 'New project', search: 'Search projects', empty: 'No projects yet', emptyDescription: 'Create a project inside a workspace to get started.', memberCount: '{{count}} people', open: 'Permissions', active: 'In progress', noDescription: 'No description.', inWorkspace: 'Workspace: {{name}}' },
      users: { title: 'Users', description: 'Manage users and memberships.', membershipDescription: 'Link existing identities and delegate roles without duplicating users.', add: 'Add membership', search: 'Search by name or email', empty: 'No users found', emptyClientDescription: 'Link an existing identity to this organization.', emptyWorkspaceDescription: 'Add someone already linked to the parent organization.', addClientTitle: 'Link user to organization', addClientDescription: 'The identity remains unique and only gains access within this organization.', addWorkspaceTitle: 'Add user to workspace', addWorkspaceDescription: 'The user must have an active membership in the parent organization.', userIdentifier: 'User ID', userIdentifierHint: 'Use the global identity identifier.', selectUser: 'Select a user', selectUserHint: 'Only active organization users who are not already in this workspace are shown.', emailHint: 'Enter the exact email of an existing identity.', initialPermissions: 'Initial permissions', initialPermissionsDescription: 'These defaults will be inherited by every project in the workspace.', configurePermissions: 'Configure permissions', makeClientAdmin: 'Make organization administrator', makeWorkspaceAdmin: 'Make workspace administrator', makeMember: 'Make member', updated: 'Membership updated.', removed: 'Membership removed and history preserved.', removeTitle: 'Remove {{name}} membership?', removeDescription: 'Access will end in this scope. Other memberships and history are preserved.', invite: 'Invite user', projectAccess: '{{count}} projects', columns: { user: 'User', projects: 'Project access', status: 'Status', created: 'Created' } },
      permissions: { title: 'Permissions', functionalTitle: 'Functional permissions', description: 'Set access levels.', functionalDescription: 'Configure workspace defaults and explicit project overrides.', scopeTitle: 'Permission scope', scope: 'Applies to', workspaceDefaults: 'Workspace defaults', projectOverride: 'Override · {{name}}', user: 'User', selectUser: 'Select a user', selectUserHint: 'Choose a person to edit their functional matrix.', noMembers: 'No participants in this scope', noMembersDescription: 'Add users before configuring access.', denyPriority: 'An explicit denial always takes priority over inherited permissions. Changes apply to subsequent requests.', saved: 'Permissions updated.', saveError: 'Unable to save permissions.', effect: 'Rule', level: 'Level', allow: 'Allow', deny: 'Deny', inherit: 'Inherit from workspace', effective: 'Effective: {{level}}', levels: { READ: 'Read', WRITE: 'Write', ADMIN: 'Admin' }, features: { PERSONA: { label: 'Personas', description: 'Create, edit, and view personas.' }, RESEARCH: { label: 'Research', description: 'Create, edit, and view questionnaires.' }, SIMULATION: { label: 'Simulation', description: 'Run and view simulation rooms.' }, DASHBOARD: { label: 'Dashboard', description: 'Access analytics and reports.' } }, permission: { VIEWER: 'Viewer', CONTRIBUTOR: 'Contributor', MANAGER: 'Manager', OWNER: 'Owner' }, permissionHint: { VIEWER: 'Can view the project and personas.', CONTRIBUTOR: 'Can also create and edit personas.', MANAGER: 'Can also manage participants and settings.', OWNER: 'Has full control of the project.' } },
      workspaces: { title: 'Workspaces', description: 'Separate projects, teams, and asset associations within the organization.', create: 'New workspace', search: 'Search workspaces', empty: 'No workspaces yet', emptyDescription: 'Create another workspace to organize projects and teams.', default: 'Default', noDescription: 'No description.', projectCount: '{{count}} projects', memberCount: '{{count}} people', open: 'Open', deleted: 'Workspace deleted.', deleteTitle: 'Delete {{name}}?', deleteDescription: 'Deletion will be blocked if it violates membership, project, or last-administrator rules.' },
      assets: { associationsSaved: 'Associations updated.', associateTitle: 'Workspaces with access to {{name}}', associateDescription: 'Associations use references. Editing the asset is reflected in every selected workspace.' },
      personas: { title: 'Personas', description: 'Manage personas once per organization and share them by reference.', create: 'New persona', createTitle: 'Create persona', createDescription: 'The persona is created in the organization and can be associated with multiple workspaces.', editTitle: 'Edit {{name}}', editDescription: 'Changes are reflected immediately in every associated workspace.', search: 'Search personas', empty: 'No personas yet', emptyDescription: 'Create the first persona for this organization.', emptyWorkspaceDescription: 'No personas are associated with this workspace.', noDescription: 'No description.', notAssociated: 'No associated workspace', manageAssociations: 'Manage associations', inUse: 'Used by {{count}} projects', updated: 'Persona updated.', deleted: 'Persona deleted.', deleteTitle: 'Delete {{name}} from the organization?', deleteDescription: 'The persona is removed from every workspace. Historical snapshots remain.', deleteBlocked: 'This persona is used by active projects and cannot be deleted.' },
      questionnaires: { title: 'Questionnaires', description: 'Manage questionnaires once per organization and share them by reference.', create: 'New questionnaire', createTitle: 'Create questionnaire', createDescription: 'The questionnaire is created in the organization and can be associated with multiple workspaces.', editTitle: 'Edit {{name}}', editDescription: 'Changes are reflected immediately in every associated workspace.', search: 'Search questionnaires', empty: 'No questionnaires yet', emptyDescription: 'Create the first questionnaire for this organization.', emptyWorkspaceDescription: 'No questionnaires are associated with this workspace.', noDescription: 'No description.', notAssociated: 'No associated workspace', manageAssociations: 'Manage associations', inUse: 'Used by {{count}} projects', updated: 'Questionnaire updated.', deleted: 'Questionnaire deleted.', deleteTitle: 'Delete {{name}} from the organization?', deleteDescription: 'The questionnaire is removed from every workspace. Historical snapshots remain.', deleteBlocked: 'This questionnaire is used by active projects and cannot be deleted.' },
      forbidden: { title: 'You do not have access to this area', description: 'Your profile lacks the required permission. Contact your account administrator if this seems incorrect.' },
      roles: { SUPER_ADMIN: 'Super administrator', CLIENT_ADMIN: 'Organization administrator', CLIENT_MEMBER: 'Organization member', WORKSPACE_ADMIN: 'Workspace administrator', WORKSPACE_MEMBER: 'Workspace member', PROJECT_USER: 'Project user' },
    },
  },
} as const;

export type AppLocale = keyof typeof resources;
export const supportedLocales = Object.keys(resources) as AppLocale[];
