export const resources = {
  'pt-BR': {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Carregando', retry: 'Tentar novamente', cancel: 'Cancelar', save: 'Salvar alterações', create: 'Criar', search: 'Buscar', actions: 'Ações', status: 'Status', active: 'Ativo', invited: 'Convidado', suspended: 'Suspenso', archived: 'Arquivado', openMenu: 'Abrir menu', close: 'Fechar', previous: 'Anterior', next: 'Próxima', page: 'Página {{current}} de {{total}}', noResults: 'Nenhum resultado', edit: 'Editar', unknown: 'Não informado', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Escuro', system: 'Sistema', signOut: 'Sair', account: 'Conta', menu: 'Menu', email: 'E-mail', password: 'Senha', name: 'Nome', tenant: 'Cliente', members: 'pessoas', projects: 'projetos', updatedAt: 'Atualizado em', createdAt: 'Criado em', permissions: 'Permissões', accessDenied: 'Acesso negado', backHome: 'Voltar à visão geral', notFound: 'Página não encontrada', notFoundDescription: 'O endereço pode ter mudado ou não existe.', errorTitle: 'Não foi possível carregar', errorDescription: 'Confira sua conexão e tente novamente.'
      },
      auth: {
        title: 'Acesse seu espaço de trabalho', subtitle: 'Administre clientes, projetos e permissões com segurança.', emailPlaceholder: 'voce@empresa.com', passwordPlaceholder: 'Sua senha', submit: 'Entrar', submitting: 'Entrando…', invalidCredentials: 'E-mail ou senha incorretos.', genericError: 'Não foi possível entrar agora. Tente novamente.', secureSession: 'Sua sessão é protegida por cookie seguro. A senha nunca fica salva neste dispositivo.', expired: 'Sua sessão expirou. Entre novamente.'
      },
      validation: { required: 'Campo obrigatório.', email: 'Informe um e-mail válido.', passwordLength: 'Use pelo menos 8 caracteres.' },
      forms: {
        error: 'Não foi possível concluir. Revise os dados e tente novamente.', created: 'Cadastro concluído com sucesso.', moved: 'Usuário movido para o novo projeto.', tenantName: 'Nome do cliente', slug: 'Identificador', initialAdmin: 'Administrador inicial', passwordHint: 'Use 12 ou mais caracteres, com maiúscula, minúscula, número e símbolo.', description: 'Descrição', projects: 'Projetos iniciais', projectsHint: 'Opcional. Você poderá alterar os projetos depois.', initialPermission: 'Permissão inicial', selectTenant: 'Selecione um cliente', selectProject: 'Selecione um projeto', fromProject: 'Projeto de origem', toProject: 'Projeto de destino', moveUser: 'Mover entre projetos', createTenantTitle: 'Novo cliente e administrador', createTenantDescription: 'O cliente será criado isoladamente com seu primeiro administrador.', createAdminTitle: 'Novo administrador', createAdminDescription: 'O administrador terá acesso somente ao cliente selecionado.', createProjectTitle: 'Novo projeto', createProjectDescription: 'Crie um espaço para reunir pessoas, pesquisas e personas.', createUserTitle: 'Novo usuário', createUserDescription: 'Cadastre a pessoa e, se quiser, atribua projetos e um preset de permissão.', moveUserTitle: 'Mover {{name}}', moveUserDescription: 'O acesso será removido do projeto de origem e criado no destino.', validation: { name: 'Use pelo menos 2 caracteres.', slug: 'Use apenas letras minúsculas, números e hífens.', password: 'A senha não atende aos requisitos de segurança.', tenant: 'Selecione um cliente.', differentProject: 'Escolha um projeto diferente do projeto de origem.' }
      },
      nav: { overview: 'Visão geral', tenants: 'Clientes', admins: 'Administradores', projects: 'Projetos', users: 'Usuários', permissions: 'Permissões' },
      dashboard: {
        title: 'Visão geral', superDescription: 'Acompanhe clientes e administradores da plataforma.', clientDescription: 'Acompanhe os projetos e o acesso da sua equipe.', tenants: 'Clientes', admins: 'Administradores', projects: 'Projetos', users: 'Usuários', personas: 'Personas ativas', activity: 'Atividade recente', noActivity: 'Nenhuma atividade recente', noActivityDescription: 'As próximas alterações realizadas na conta aparecerão aqui.', quickActions: 'Ações rápidas', createTenant: 'Adicionar cliente', createAdmin: 'Criar administrador', createProject: 'Novo projeto', manageUsers: 'Gerenciar usuários'
      },
      tenants: {
        title: 'Clientes', description: 'Gerencie organizações isoladas e seus acessos.', create: 'Adicionar cliente', search: 'Buscar por nome ou identificador', empty: 'Nenhum cliente cadastrado', emptyDescription: 'Crie o primeiro cliente para atribuir administradores e projetos.', columns: { tenant: 'Cliente', admins: 'Administradores', projects: 'Projetos', created: 'Criação' }
      },
      admins: {
        title: 'Administradores', description: 'Controle quem administra cada cliente.', create: 'Criar administrador', search: 'Buscar por nome ou e-mail', empty: 'Nenhum administrador encontrado', emptyDescription: 'Crie um administrador e associe-o a um único cliente.', columns: { admin: 'Administrador', tenant: 'Cliente', status: 'Status', created: 'Criação' }
      },
      projects: {
        title: 'Projetos', description: 'Organize pesquisas, personas e participantes por projeto.', create: 'Novo projeto', search: 'Buscar projetos', empty: 'Nenhum projeto criado', emptyDescription: 'Crie um projeto para começar a reunir participantes e personas.', memberCount: '{{count}} pessoas', open: 'Abrir projeto', active: 'Em andamento'
      },
      users: {
        title: 'Usuários', description: 'Gerencie as pessoas do cliente e mova-as entre projetos.', invite: 'Convidar usuário', search: 'Buscar por nome ou e-mail', empty: 'Nenhum usuário encontrado', emptyDescription: 'Convide pessoas para depois atribuí-las aos projetos.', projectAccess: '{{count}} projetos', columns: { user: 'Usuário', projects: 'Acesso a projetos', status: 'Status', created: 'Criação' }
      },
      permissions: {
        title: 'Permissões por projeto', description: 'Defina o nível de acesso de cada pessoa em cada projeto.', selectProject: 'Selecionar projeto', selectProjectHint: 'Escolha um projeto para revisar participantes e permissões.', noMembers: 'Nenhum participante neste projeto', noMembersDescription: 'Adicione usuários ao projeto para configurar seus acessos.', saved: 'Permissões atualizadas.', saveError: 'Não foi possível salvar as permissões.', permission: { VIEWER: 'Leitor', CONTRIBUTOR: 'Colaborador', MANAGER: 'Gestor', OWNER: 'Responsável' }, permissionHint: { VIEWER: 'Consulta o projeto e as personas.', CONTRIBUTOR: 'Também cria e edita personas.', MANAGER: 'Também gerencia participantes e configurações.', OWNER: 'Controle completo do projeto.' }
      },
      forbidden: { title: 'Você não tem acesso a esta área', description: 'Seu perfil não possui a permissão necessária. Se isso parecer incorreto, fale com o administrador da conta.' },
      roles: { SUPER_ADMIN: 'Superadministrador', CLIENT_ADMIN: 'Administrador do cliente', PROJECT_USER: 'Usuário de projeto' },
    },
  },
  es: {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Cargando', retry: 'Intentar de nuevo', cancel: 'Cancelar', save: 'Guardar cambios', create: 'Crear', search: 'Buscar', actions: 'Acciones', status: 'Estado', active: 'Activo', invited: 'Invitado', suspended: 'Suspendido', archived: 'Archivado', openMenu: 'Abrir menú', close: 'Cerrar', previous: 'Anterior', next: 'Siguiente', page: 'Página {{current}} de {{total}}', noResults: 'Sin resultados', edit: 'Editar', unknown: 'No informado', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Oscuro', system: 'Sistema', signOut: 'Salir', account: 'Cuenta', menu: 'Menú', email: 'Correo', password: 'Contraseña', name: 'Nombre', tenant: 'Cliente', members: 'personas', projects: 'proyectos', updatedAt: 'Actualizado el', createdAt: 'Creado el', permissions: 'Permisos', accessDenied: 'Acceso denegado', backHome: 'Volver al resumen', notFound: 'Página no encontrada', notFoundDescription: 'La dirección puede haber cambiado o no existir.', errorTitle: 'No se pudo cargar', errorDescription: 'Comprueba tu conexión e inténtalo de nuevo.'
      },
      auth: { title: 'Accede a tu espacio de trabajo', subtitle: 'Administra clientes, proyectos y permisos con seguridad.', emailPlaceholder: 'tu@empresa.com', passwordPlaceholder: 'Tu contraseña', submit: 'Entrar', submitting: 'Entrando…', invalidCredentials: 'Correo o contraseña incorrectos.', genericError: 'No se pudo iniciar sesión. Inténtalo de nuevo.', secureSession: 'Tu sesión está protegida por una cookie segura. La contraseña nunca se guarda en este dispositivo.', expired: 'Tu sesión expiró. Inicia sesión nuevamente.' },
      validation: { required: 'Campo obligatorio.', email: 'Introduce un correo válido.', passwordLength: 'Usa al menos 8 caracteres.' },
      forms: {
        error: 'No se pudo completar. Revisa los datos e inténtalo de nuevo.', created: 'Registro completado correctamente.', moved: 'Usuario movido al nuevo proyecto.', tenantName: 'Nombre del cliente', slug: 'Identificador', initialAdmin: 'Administrador inicial', passwordHint: 'Usa 12 o más caracteres, con mayúscula, minúscula, número y símbolo.', description: 'Descripción', projects: 'Proyectos iniciales', projectsHint: 'Opcional. Podrás cambiar los proyectos después.', initialPermission: 'Permiso inicial', selectTenant: 'Selecciona un cliente', selectProject: 'Selecciona un proyecto', fromProject: 'Proyecto de origen', toProject: 'Proyecto de destino', moveUser: 'Mover entre proyectos', createTenantTitle: 'Nuevo cliente y administrador', createTenantDescription: 'El cliente se creará de forma aislada con su primer administrador.', createAdminTitle: 'Nuevo administrador', createAdminDescription: 'El administrador solo tendrá acceso al cliente seleccionado.', createProjectTitle: 'Nuevo proyecto', createProjectDescription: 'Crea un espacio para reunir personas, encuestas y personas.', createUserTitle: 'Nuevo usuario', createUserDescription: 'Registra a la persona y asigna proyectos y un preset de permisos.', moveUserTitle: 'Mover a {{name}}', moveUserDescription: 'El acceso se eliminará del proyecto de origen y se creará en el destino.', validation: { name: 'Usa al menos 2 caracteres.', slug: 'Usa solo minúsculas, números y guiones.', password: 'La contraseña no cumple los requisitos de seguridad.', tenant: 'Selecciona un cliente.', differentProject: 'Elige un proyecto diferente al de origen.' }
      },
      nav: { overview: 'Resumen', tenants: 'Clientes', admins: 'Administradores', projects: 'Proyectos', users: 'Usuarios', permissions: 'Permisos' },
      dashboard: { title: 'Resumen', superDescription: 'Supervisa clientes y administradores de la plataforma.', clientDescription: 'Supervisa proyectos y accesos de tu equipo.', tenants: 'Clientes', admins: 'Administradores', projects: 'Proyectos', users: 'Usuarios', personas: 'Personas activas', activity: 'Actividad reciente', noActivity: 'Sin actividad reciente', noActivityDescription: 'Los próximos cambios aparecerán aquí.', quickActions: 'Acciones rápidas', createTenant: 'Añadir cliente', createAdmin: 'Crear administrador', createProject: 'Nuevo proyecto', manageUsers: 'Gestionar usuarios' },
      tenants: { title: 'Clientes', description: 'Gestiona organizaciones aisladas y sus accesos.', create: 'Añadir cliente', search: 'Buscar por nombre o identificador', empty: 'No hay clientes', emptyDescription: 'Crea el primer cliente para asignar administradores y proyectos.', columns: { tenant: 'Cliente', admins: 'Administradores', projects: 'Proyectos', created: 'Creación' } },
      admins: { title: 'Administradores', description: 'Controla quién administra cada cliente.', create: 'Crear administrador', search: 'Buscar por nombre o correo', empty: 'No hay administradores', emptyDescription: 'Crea un administrador y asígnalo a un único cliente.', columns: { admin: 'Administrador', tenant: 'Cliente', status: 'Estado', created: 'Creación' } },
      projects: { title: 'Proyectos', description: 'Organiza encuestas, personas y participantes por proyecto.', create: 'Nuevo proyecto', search: 'Buscar proyectos', empty: 'No hay proyectos', emptyDescription: 'Crea un proyecto para reunir participantes y personas.', memberCount: '{{count}} personas', open: 'Abrir proyecto', active: 'En curso' },
      users: { title: 'Usuarios', description: 'Gestiona usuarios del cliente y muévelos entre proyectos.', invite: 'Invitar usuario', search: 'Buscar por nombre o correo', empty: 'No hay usuarios', emptyDescription: 'Invita personas para asignarlas a proyectos.', projectAccess: '{{count}} proyectos', columns: { user: 'Usuario', projects: 'Acceso a proyectos', status: 'Estado', created: 'Creación' } },
      permissions: { title: 'Permisos por proyecto', description: 'Define el nivel de acceso de cada persona en cada proyecto.', selectProject: 'Seleccionar proyecto', selectProjectHint: 'Elige un proyecto para revisar participantes y permisos.', noMembers: 'No hay participantes', noMembersDescription: 'Añade usuarios al proyecto para configurar su acceso.', saved: 'Permisos actualizados.', saveError: 'No se pudieron guardar los permisos.', permission: { VIEWER: 'Lector', CONTRIBUTOR: 'Colaborador', MANAGER: 'Gestor', OWNER: 'Responsable' }, permissionHint: { VIEWER: 'Consulta el proyecto y las personas.', CONTRIBUTOR: 'También crea y edita personas.', MANAGER: 'También gestiona participantes y ajustes.', OWNER: 'Control completo del proyecto.' } },
      forbidden: { title: 'No tienes acceso a esta área', description: 'Tu perfil no tiene el permiso necesario. Contacta al administrador si crees que es un error.' },
      roles: { SUPER_ADMIN: 'Superadministrador', CLIENT_ADMIN: 'Administrador del cliente', PROJECT_USER: 'Usuario de proyecto' },
    },
  },
  en: {
    translation: {
      common: {
        appName: 'PersonaIA', loading: 'Loading', retry: 'Try again', cancel: 'Cancel', save: 'Save changes', create: 'Create', search: 'Search', actions: 'Actions', status: 'Status', active: 'Active', invited: 'Invited', suspended: 'Suspended', archived: 'Archived', openMenu: 'Open menu', close: 'Close', previous: 'Previous', next: 'Next', page: 'Page {{current}} of {{total}}', noResults: 'No results', edit: 'Edit', unknown: 'Not provided', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', system: 'System', signOut: 'Sign out', account: 'Account', menu: 'Menu', email: 'Email', password: 'Password', name: 'Name', tenant: 'Client', members: 'people', projects: 'projects', updatedAt: 'Updated', createdAt: 'Created', permissions: 'Permissions', accessDenied: 'Access denied', backHome: 'Back to overview', notFound: 'Page not found', notFoundDescription: 'This address may have changed or does not exist.', errorTitle: 'Unable to load', errorDescription: 'Check your connection and try again.'
      },
      auth: { title: 'Access your workspace', subtitle: 'Manage clients, projects, and permissions securely.', emailPlaceholder: 'you@company.com', passwordPlaceholder: 'Your password', submit: 'Sign in', submitting: 'Signing in…', invalidCredentials: 'Incorrect email or password.', genericError: 'Unable to sign in right now. Try again.', secureSession: 'Your session is protected by a secure cookie. Your password is never saved on this device.', expired: 'Your session expired. Sign in again.' },
      validation: { required: 'Required field.', email: 'Enter a valid email.', passwordLength: 'Use at least 8 characters.' },
      forms: {
        error: 'Unable to complete this action. Review the data and try again.', created: 'Successfully created.', moved: 'User moved to the new project.', tenantName: 'Client name', slug: 'Identifier', initialAdmin: 'Initial administrator', passwordHint: 'Use 12 or more characters with uppercase, lowercase, a number, and a symbol.', description: 'Description', projects: 'Initial projects', projectsHint: 'Optional. You can change project access later.', initialPermission: 'Initial permission', selectTenant: 'Select a client', selectProject: 'Select a project', fromProject: 'Source project', toProject: 'Destination project', moveUser: 'Move between projects', createTenantTitle: 'New client and administrator', createTenantDescription: 'The client will be created in isolation with its first administrator.', createAdminTitle: 'New administrator', createAdminDescription: 'The administrator will only have access to the selected client.', createProjectTitle: 'New project', createProjectDescription: 'Create a space to gather people, surveys, and personas.', createUserTitle: 'New user', createUserDescription: 'Register the person and optionally assign projects and a permission preset.', moveUserTitle: 'Move {{name}}', moveUserDescription: 'Access will be removed from the source project and created in the destination.', validation: { name: 'Use at least 2 characters.', slug: 'Use lowercase letters, numbers, and hyphens only.', password: 'The password does not meet the security requirements.', tenant: 'Select a client.', differentProject: 'Choose a project different from the source.' }
      },
      nav: { overview: 'Overview', tenants: 'Clients', admins: 'Administrators', projects: 'Projects', users: 'Users', permissions: 'Permissions' },
      dashboard: { title: 'Overview', superDescription: 'Monitor clients and platform administrators.', clientDescription: 'Monitor your team’s projects and access.', tenants: 'Clients', admins: 'Administrators', projects: 'Projects', users: 'Users', personas: 'Active personas', activity: 'Recent activity', noActivity: 'No recent activity', noActivityDescription: 'Upcoming account changes will appear here.', quickActions: 'Quick actions', createTenant: 'Add client', createAdmin: 'Create administrator', createProject: 'New project', manageUsers: 'Manage users' },
      tenants: { title: 'Clients', description: 'Manage isolated organizations and their access.', create: 'Add client', search: 'Search by name or identifier', empty: 'No clients yet', emptyDescription: 'Create the first client to assign administrators and projects.', columns: { tenant: 'Client', admins: 'Administrators', projects: 'Projects', created: 'Created' } },
      admins: { title: 'Administrators', description: 'Control who administers each client.', create: 'Create administrator', search: 'Search by name or email', empty: 'No administrators found', emptyDescription: 'Create an administrator and assign them to one client.', columns: { admin: 'Administrator', tenant: 'Client', status: 'Status', created: 'Created' } },
      projects: { title: 'Projects', description: 'Organize surveys, personas, and participants by project.', create: 'New project', search: 'Search projects', empty: 'No projects yet', emptyDescription: 'Create a project to start gathering participants and personas.', memberCount: '{{count}} people', open: 'Open project', active: 'In progress' },
      users: { title: 'Users', description: 'Manage client users and move them between projects.', invite: 'Invite user', search: 'Search by name or email', empty: 'No users found', emptyDescription: 'Invite people, then assign them to projects.', projectAccess: '{{count}} projects', columns: { user: 'User', projects: 'Project access', status: 'Status', created: 'Created' } },
      permissions: { title: 'Permissions by project', description: 'Set each person’s access level for every project.', selectProject: 'Select project', selectProjectHint: 'Choose a project to review participants and permissions.', noMembers: 'No participants in this project', noMembersDescription: 'Add users to the project to configure their access.', saved: 'Permissions updated.', saveError: 'Unable to save permissions.', permission: { VIEWER: 'Viewer', CONTRIBUTOR: 'Contributor', MANAGER: 'Manager', OWNER: 'Owner' }, permissionHint: { VIEWER: 'Can view the project and personas.', CONTRIBUTOR: 'Can also create and edit personas.', MANAGER: 'Can also manage participants and settings.', OWNER: 'Has full control of the project.' } },
      forbidden: { title: 'You do not have access to this area', description: 'Your profile lacks the required permission. Contact your account administrator if this seems incorrect.' },
      roles: { SUPER_ADMIN: 'Super administrator', CLIENT_ADMIN: 'Client administrator', PROJECT_USER: 'Project user' },
    },
  },
} as const;

export type AppLocale = keyof typeof resources;
export const supportedLocales = Object.keys(resources) as AppLocale[];
